// @ts-check

/**
 * Auto-generated from the docs/ folder — drop in a new `docs/<slug>.md`
 * case study and it appears here automatically.
 *
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */
const sidebars = {
  projectsSidebar: [{type: 'autogenerated', dirName: '.'}],
};

export default sidebars;
